### ISSUE TITLE
Grammatical errors in 'question.md'

### ISSUE THREAD

**Issue by th-bunratta** [magmagcup/somequiz#1]
In the following lines as follows in [question.md](question.md), please review your writing.
**Note:** errors will be incrementally posted here.

https://github.com/magmagcup/somequiz/blob/1b3fd01272ca5471b3afa11d59a0bb4351e54110/question.md#L3
- A Subject/Verb agreement error

https://github.com/magmagcup/somequiz/blob/1b3fd01272ca5471b3afa11d59a0bb4351e54110/question.md#L45-L47
- The missing article (an or the?)

**Comment by MaiMee1** [comment]
https://github.com/magmagcup/somequiz/blob/1b3fd01272ca5471b3afa11d59a0bb4351e54110/question.md#L43-L48

There is also a punctuation error on lines 46 and 48:
```diff
- input, Repeat
```

**Comment by MaiMee1** [comment]
https://github.com/magmagcup/somequiz/blob/1b3fd01272ca5471b3afa11d59a0bb4351e54110/question.md#L61-L63

On line 61, using a colon ":" would also be better.

**Comment by th-bunratta** [comment]
https://github.com/magmagcup/somequiz/blob/1b3fd01272ca5471b3afa11d59a0bb4351e54110/question.md#L61-L63
On the same line, S/V agreement rules weren't properly applied.

**Comment by magmagcup** [comment]
First thanks for reviewing my code! 
//Finally finish fixing all of the problems according to your guys suggestion!
